package com.goldcard.goldcardiot.models;

public class SysCodeTable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_code_table.id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_code_table.sys_id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private String sysId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_code_table.module_id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private String moduleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_code_table.table_name
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private String tableName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_code_table.field_name
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private String fieldName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_code_table.key
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private String key;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_code_table.value
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private String value;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_code_table.des
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private String des;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_code_table.orderid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private Integer orderid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_code_table.id
	 * @return  the value of sys_code_table.id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_code_table.id
	 * @param id  the value for sys_code_table.id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_code_table.sys_id
	 * @return  the value of sys_code_table.sys_id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public String getSysId() {
		return sysId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_code_table.sys_id
	 * @param sysId  the value for sys_code_table.sys_id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setSysId(String sysId) {
		this.sysId = sysId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_code_table.module_id
	 * @return  the value of sys_code_table.module_id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public String getModuleId() {
		return moduleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_code_table.module_id
	 * @param moduleId  the value for sys_code_table.module_id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setModuleId(String moduleId) {
		this.moduleId = moduleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_code_table.table_name
	 * @return  the value of sys_code_table.table_name
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public String getTableName() {
		return tableName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_code_table.table_name
	 * @param tableName  the value for sys_code_table.table_name
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_code_table.field_name
	 * @return  the value of sys_code_table.field_name
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public String getFieldName() {
		return fieldName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_code_table.field_name
	 * @param fieldName  the value for sys_code_table.field_name
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_code_table.key
	 * @return  the value of sys_code_table.key
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public String getKey() {
		return key;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_code_table.key
	 * @param key  the value for sys_code_table.key
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setKey(String key) {
		this.key = key;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_code_table.value
	 * @return  the value of sys_code_table.value
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_code_table.value
	 * @param value  the value for sys_code_table.value
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_code_table.des
	 * @return  the value of sys_code_table.des
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public String getDes() {
		return des;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_code_table.des
	 * @param des  the value for sys_code_table.des
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setDes(String des) {
		this.des = des;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_code_table.orderid
	 * @return  the value of sys_code_table.orderid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public Integer getOrderid() {
		return orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_code_table.orderid
	 * @param orderid  the value for sys_code_table.orderid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setOrderid(Integer orderid) {
		this.orderid = orderid;
	}
}