package com.goldcard.goldcardiot.models;

public class SysDeptType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dept_type.id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dept_type.no
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private String no;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dept_type.name
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dept_type.remark
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dept_type.id
	 * @return  the value of sys_dept_type.id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dept_type.id
	 * @param id  the value for sys_dept_type.id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dept_type.no
	 * @return  the value of sys_dept_type.no
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public String getNo() {
		return no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dept_type.no
	 * @param no  the value for sys_dept_type.no
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setNo(String no) {
		this.no = no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dept_type.name
	 * @return  the value of sys_dept_type.name
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dept_type.name
	 * @param name  the value for sys_dept_type.name
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dept_type.remark
	 * @return  the value of sys_dept_type.remark
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dept_type.remark
	 * @param remark  the value for sys_dept_type.remark
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}