package com.goldcard.goldcardiot.models;

public class SysDeptAndRight {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dept_and_right.id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dept_and_right.deptid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private Integer deptid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dept_and_right.sysrightid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private Integer sysrightid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dept_and_right.userid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dept_and_right.userdeptid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private Integer userdeptid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dept_and_right.id
	 * @return  the value of sys_dept_and_right.id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dept_and_right.id
	 * @param id  the value for sys_dept_and_right.id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dept_and_right.deptid
	 * @return  the value of sys_dept_and_right.deptid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public Integer getDeptid() {
		return deptid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dept_and_right.deptid
	 * @param deptid  the value for sys_dept_and_right.deptid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setDeptid(Integer deptid) {
		this.deptid = deptid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dept_and_right.sysrightid
	 * @return  the value of sys_dept_and_right.sysrightid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public Integer getSysrightid() {
		return sysrightid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dept_and_right.sysrightid
	 * @param sysrightid  the value for sys_dept_and_right.sysrightid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setSysrightid(Integer sysrightid) {
		this.sysrightid = sysrightid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dept_and_right.userid
	 * @return  the value of sys_dept_and_right.userid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dept_and_right.userid
	 * @param userid  the value for sys_dept_and_right.userid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dept_and_right.userdeptid
	 * @return  the value of sys_dept_and_right.userdeptid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public Integer getUserdeptid() {
		return userdeptid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dept_and_right.userdeptid
	 * @param userdeptid  the value for sys_dept_and_right.userdeptid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setUserdeptid(Integer userdeptid) {
		this.userdeptid = userdeptid;
	}
}