package com.goldcard.goldcardiot.models;

public class SysDeptAndType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dept_and_type.id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dept_and_type.deptid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private Integer deptid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dept_and_type.typeid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private Integer typeid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dept_and_type.id
	 * @return  the value of sys_dept_and_type.id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dept_and_type.id
	 * @param id  the value for sys_dept_and_type.id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dept_and_type.deptid
	 * @return  the value of sys_dept_and_type.deptid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public Integer getDeptid() {
		return deptid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dept_and_type.deptid
	 * @param deptid  the value for sys_dept_and_type.deptid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setDeptid(Integer deptid) {
		this.deptid = deptid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dept_and_type.typeid
	 * @return  the value of sys_dept_and_type.typeid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public Integer getTypeid() {
		return typeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dept_and_type.typeid
	 * @param typeid  the value for sys_dept_and_type.typeid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setTypeid(Integer typeid) {
		this.typeid = typeid;
	}
}