package com.goldcard.goldcardiot.models;

public class SysDept {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dept.id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dept.father_id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private Integer fatherId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dept.no
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private String no;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dept.name
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dept.shortname
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private String shortname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dept.type
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dept.longitude
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private String longitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dept.latitude
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private String latitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dept.img_url
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private String imgUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dept.orderid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private Integer orderid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dept.isdel
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private Integer isdel = 0; //默认值0
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dept.remark
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dept.id
	 * @return  the value of sys_dept.id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dept.id
	 * @param id  the value for sys_dept.id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dept.father_id
	 * @return  the value of sys_dept.father_id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public Integer getFatherId() {
		return fatherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dept.father_id
	 * @param fatherId  the value for sys_dept.father_id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setFatherId(Integer fatherId) {
		this.fatherId = fatherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dept.no
	 * @return  the value of sys_dept.no
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public String getNo() {
		return no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dept.no
	 * @param no  the value for sys_dept.no
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setNo(String no) {
		this.no = no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dept.name
	 * @return  the value of sys_dept.name
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dept.name
	 * @param name  the value for sys_dept.name
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dept.shortname
	 * @return  the value of sys_dept.shortname
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public String getShortname() {
		return shortname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dept.shortname
	 * @param shortname  the value for sys_dept.shortname
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setShortname(String shortname) {
		this.shortname = shortname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dept.type
	 * @return  the value of sys_dept.type
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dept.type
	 * @param type  the value for sys_dept.type
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dept.longitude
	 * @return  the value of sys_dept.longitude
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public String getLongitude() {
		return longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dept.longitude
	 * @param longitude  the value for sys_dept.longitude
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dept.latitude
	 * @return  the value of sys_dept.latitude
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public String getLatitude() {
		return latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dept.latitude
	 * @param latitude  the value for sys_dept.latitude
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dept.img_url
	 * @return  the value of sys_dept.img_url
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public String getImgUrl() {
		return imgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dept.img_url
	 * @param imgUrl  the value for sys_dept.img_url
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dept.orderid
	 * @return  the value of sys_dept.orderid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public Integer getOrderid() {
		return orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dept.orderid
	 * @param orderid  the value for sys_dept.orderid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setOrderid(Integer orderid) {
		this.orderid = orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dept.isdel
	 * @return  the value of sys_dept.isdel
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public Integer getIsdel() {
		return isdel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dept.isdel
	 * @param isdel  the value for sys_dept.isdel
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setIsdel(Integer isdel) {
		this.isdel = isdel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dept.remark
	 * @return  the value of sys_dept.remark
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dept.remark
	 * @param remark  the value for sys_dept.remark
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}