package com.goldcard.goldcardiot.models;

public class SysRight {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_right.id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_right.father_id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private Integer fatherId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_right.level
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private Integer level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_right.icon
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private String icon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_right.url
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_right.name
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_right.childrights
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private Integer childrights;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_right.orderid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private Integer orderid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_right.id
	 * @return  the value of sys_right.id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_right.id
	 * @param id  the value for sys_right.id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_right.father_id
	 * @return  the value of sys_right.father_id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public Integer getFatherId() {
		return fatherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_right.father_id
	 * @param fatherId  the value for sys_right.father_id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setFatherId(Integer fatherId) {
		this.fatherId = fatherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_right.level
	 * @return  the value of sys_right.level
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public Integer getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_right.level
	 * @param level  the value for sys_right.level
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_right.icon
	 * @return  the value of sys_right.icon
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_right.icon
	 * @param icon  the value for sys_right.icon
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setIcon(String icon) {
		this.icon = icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_right.url
	 * @return  the value of sys_right.url
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_right.url
	 * @param url  the value for sys_right.url
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_right.name
	 * @return  the value of sys_right.name
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_right.name
	 * @param name  the value for sys_right.name
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_right.childrights
	 * @return  the value of sys_right.childrights
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public Integer getChildrights() {
		return childrights;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_right.childrights
	 * @param childrights  the value for sys_right.childrights
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setChildrights(Integer childrights) {
		this.childrights = childrights;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_right.orderid
	 * @return  the value of sys_right.orderid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public Integer getOrderid() {
		return orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_right.orderid
	 * @param orderid  the value for sys_right.orderid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setOrderid(Integer orderid) {
		this.orderid = orderid;
	}
}