package com.goldcard.goldcardiot.models;

public class SysRightAndDept {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_right_and_dept.rdid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private Integer rdid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_right_and_dept.rid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private Integer rid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_right_and_dept.did
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private Integer did;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_right_and_dept.rdid
	 * @return  the value of sys_right_and_dept.rdid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public Integer getRdid() {
		return rdid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_right_and_dept.rdid
	 * @param rdid  the value for sys_right_and_dept.rdid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setRdid(Integer rdid) {
		this.rdid = rdid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_right_and_dept.rid
	 * @return  the value of sys_right_and_dept.rid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public Integer getRid() {
		return rid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_right_and_dept.rid
	 * @param rid  the value for sys_right_and_dept.rid
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setRid(Integer rid) {
		this.rid = rid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_right_and_dept.did
	 * @return  the value of sys_right_and_dept.did
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public Integer getDid() {
		return did;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_right_and_dept.did
	 * @param did  the value for sys_right_and_dept.did
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setDid(Integer did) {
		this.did = did;
	}
}