package com.goldcard.goldcardiot.models;

public class SysRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.creator
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private Integer creator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.no
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private String no;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.name
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.remark
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.id
	 * @return  the value of sys_role.id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.id
	 * @param id  the value for sys_role.id
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.creator
	 * @return  the value of sys_role.creator
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public Integer getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.creator
	 * @param creator  the value for sys_role.creator
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setCreator(Integer creator) {
		this.creator = creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.no
	 * @return  the value of sys_role.no
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public String getNo() {
		return no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.no
	 * @param no  the value for sys_role.no
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setNo(String no) {
		this.no = no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.name
	 * @return  the value of sys_role.name
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.name
	 * @param name  the value for sys_role.name
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.remark
	 * @return  the value of sys_role.remark
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.remark
	 * @param remark  the value for sys_role.remark
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}