package com.goldcard.goldcardiot.models;

import java.util.ArrayList;
import java.util.List;

public class SysUserOnlineExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_user_online
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_user_online
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_user_online
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_online
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public SysUserOnlineExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_online
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_online
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_online
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_online
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_online
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_online
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_online
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_online
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_online
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_online
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_user_online
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Integer value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Integer value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Integer value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Integer value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Integer> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Integer> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Integer value1, Integer value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andStimeIsNull() {
			addCriterion("stime is null");
			return (Criteria) this;
		}

		public Criteria andStimeIsNotNull() {
			addCriterion("stime is not null");
			return (Criteria) this;
		}

		public Criteria andStimeEqualTo(String value) {
			addCriterion("stime =", value, "stime");
			return (Criteria) this;
		}

		public Criteria andStimeNotEqualTo(String value) {
			addCriterion("stime <>", value, "stime");
			return (Criteria) this;
		}

		public Criteria andStimeGreaterThan(String value) {
			addCriterion("stime >", value, "stime");
			return (Criteria) this;
		}

		public Criteria andStimeGreaterThanOrEqualTo(String value) {
			addCriterion("stime >=", value, "stime");
			return (Criteria) this;
		}

		public Criteria andStimeLessThan(String value) {
			addCriterion("stime <", value, "stime");
			return (Criteria) this;
		}

		public Criteria andStimeLessThanOrEqualTo(String value) {
			addCriterion("stime <=", value, "stime");
			return (Criteria) this;
		}

		public Criteria andStimeLike(String value) {
			addCriterion("stime like", value, "stime");
			return (Criteria) this;
		}

		public Criteria andStimeNotLike(String value) {
			addCriterion("stime not like", value, "stime");
			return (Criteria) this;
		}

		public Criteria andStimeIn(List<String> values) {
			addCriterion("stime in", values, "stime");
			return (Criteria) this;
		}

		public Criteria andStimeNotIn(List<String> values) {
			addCriterion("stime not in", values, "stime");
			return (Criteria) this;
		}

		public Criteria andStimeBetween(String value1, String value2) {
			addCriterion("stime between", value1, value2, "stime");
			return (Criteria) this;
		}

		public Criteria andStimeNotBetween(String value1, String value2) {
			addCriterion("stime not between", value1, value2, "stime");
			return (Criteria) this;
		}

		public Criteria andEtimeIsNull() {
			addCriterion("etime is null");
			return (Criteria) this;
		}

		public Criteria andEtimeIsNotNull() {
			addCriterion("etime is not null");
			return (Criteria) this;
		}

		public Criteria andEtimeEqualTo(String value) {
			addCriterion("etime =", value, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeNotEqualTo(String value) {
			addCriterion("etime <>", value, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeGreaterThan(String value) {
			addCriterion("etime >", value, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeGreaterThanOrEqualTo(String value) {
			addCriterion("etime >=", value, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeLessThan(String value) {
			addCriterion("etime <", value, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeLessThanOrEqualTo(String value) {
			addCriterion("etime <=", value, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeLike(String value) {
			addCriterion("etime like", value, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeNotLike(String value) {
			addCriterion("etime not like", value, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeIn(List<String> values) {
			addCriterion("etime in", values, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeNotIn(List<String> values) {
			addCriterion("etime not in", values, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeBetween(String value1, String value2) {
			addCriterion("etime between", value1, value2, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeNotBetween(String value1, String value2) {
			addCriterion("etime not between", value1, value2, "etime");
			return (Criteria) this;
		}

		public Criteria andSessionIdIsNull() {
			addCriterion("session_id is null");
			return (Criteria) this;
		}

		public Criteria andSessionIdIsNotNull() {
			addCriterion("session_id is not null");
			return (Criteria) this;
		}

		public Criteria andSessionIdEqualTo(String value) {
			addCriterion("session_id =", value, "sessionId");
			return (Criteria) this;
		}

		public Criteria andSessionIdNotEqualTo(String value) {
			addCriterion("session_id <>", value, "sessionId");
			return (Criteria) this;
		}

		public Criteria andSessionIdGreaterThan(String value) {
			addCriterion("session_id >", value, "sessionId");
			return (Criteria) this;
		}

		public Criteria andSessionIdGreaterThanOrEqualTo(String value) {
			addCriterion("session_id >=", value, "sessionId");
			return (Criteria) this;
		}

		public Criteria andSessionIdLessThan(String value) {
			addCriterion("session_id <", value, "sessionId");
			return (Criteria) this;
		}

		public Criteria andSessionIdLessThanOrEqualTo(String value) {
			addCriterion("session_id <=", value, "sessionId");
			return (Criteria) this;
		}

		public Criteria andSessionIdLike(String value) {
			addCriterion("session_id like", value, "sessionId");
			return (Criteria) this;
		}

		public Criteria andSessionIdNotLike(String value) {
			addCriterion("session_id not like", value, "sessionId");
			return (Criteria) this;
		}

		public Criteria andSessionIdIn(List<String> values) {
			addCriterion("session_id in", values, "sessionId");
			return (Criteria) this;
		}

		public Criteria andSessionIdNotIn(List<String> values) {
			addCriterion("session_id not in", values, "sessionId");
			return (Criteria) this;
		}

		public Criteria andSessionIdBetween(String value1, String value2) {
			addCriterion("session_id between", value1, value2, "sessionId");
			return (Criteria) this;
		}

		public Criteria andSessionIdNotBetween(String value1, String value2) {
			addCriterion("session_id not between", value1, value2, "sessionId");
			return (Criteria) this;
		}

		public Criteria andFmIsNull() {
			addCriterion("fm is null");
			return (Criteria) this;
		}

		public Criteria andFmIsNotNull() {
			addCriterion("fm is not null");
			return (Criteria) this;
		}

		public Criteria andFmEqualTo(String value) {
			addCriterion("fm =", value, "fm");
			return (Criteria) this;
		}

		public Criteria andFmNotEqualTo(String value) {
			addCriterion("fm <>", value, "fm");
			return (Criteria) this;
		}

		public Criteria andFmGreaterThan(String value) {
			addCriterion("fm >", value, "fm");
			return (Criteria) this;
		}

		public Criteria andFmGreaterThanOrEqualTo(String value) {
			addCriterion("fm >=", value, "fm");
			return (Criteria) this;
		}

		public Criteria andFmLessThan(String value) {
			addCriterion("fm <", value, "fm");
			return (Criteria) this;
		}

		public Criteria andFmLessThanOrEqualTo(String value) {
			addCriterion("fm <=", value, "fm");
			return (Criteria) this;
		}

		public Criteria andFmLike(String value) {
			addCriterion("fm like", value, "fm");
			return (Criteria) this;
		}

		public Criteria andFmNotLike(String value) {
			addCriterion("fm not like", value, "fm");
			return (Criteria) this;
		}

		public Criteria andFmIn(List<String> values) {
			addCriterion("fm in", values, "fm");
			return (Criteria) this;
		}

		public Criteria andFmNotIn(List<String> values) {
			addCriterion("fm not in", values, "fm");
			return (Criteria) this;
		}

		public Criteria andFmBetween(String value1, String value2) {
			addCriterion("fm between", value1, value2, "fm");
			return (Criteria) this;
		}

		public Criteria andFmNotBetween(String value1, String value2) {
			addCriterion("fm not between", value1, value2, "fm");
			return (Criteria) this;
		}

		public Criteria andIpIsNull() {
			addCriterion("ip is null");
			return (Criteria) this;
		}

		public Criteria andIpIsNotNull() {
			addCriterion("ip is not null");
			return (Criteria) this;
		}

		public Criteria andIpEqualTo(String value) {
			addCriterion("ip =", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotEqualTo(String value) {
			addCriterion("ip <>", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpGreaterThan(String value) {
			addCriterion("ip >", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpGreaterThanOrEqualTo(String value) {
			addCriterion("ip >=", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLessThan(String value) {
			addCriterion("ip <", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLessThanOrEqualTo(String value) {
			addCriterion("ip <=", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLike(String value) {
			addCriterion("ip like", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotLike(String value) {
			addCriterion("ip not like", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpIn(List<String> values) {
			addCriterion("ip in", values, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotIn(List<String> values) {
			addCriterion("ip not in", values, "ip");
			return (Criteria) this;
		}

		public Criteria andIpBetween(String value1, String value2) {
			addCriterion("ip between", value1, value2, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotBetween(String value1, String value2) {
			addCriterion("ip not between", value1, value2, "ip");
			return (Criteria) this;
		}

		public Criteria andMacIsNull() {
			addCriterion("mac is null");
			return (Criteria) this;
		}

		public Criteria andMacIsNotNull() {
			addCriterion("mac is not null");
			return (Criteria) this;
		}

		public Criteria andMacEqualTo(String value) {
			addCriterion("mac =", value, "mac");
			return (Criteria) this;
		}

		public Criteria andMacNotEqualTo(String value) {
			addCriterion("mac <>", value, "mac");
			return (Criteria) this;
		}

		public Criteria andMacGreaterThan(String value) {
			addCriterion("mac >", value, "mac");
			return (Criteria) this;
		}

		public Criteria andMacGreaterThanOrEqualTo(String value) {
			addCriterion("mac >=", value, "mac");
			return (Criteria) this;
		}

		public Criteria andMacLessThan(String value) {
			addCriterion("mac <", value, "mac");
			return (Criteria) this;
		}

		public Criteria andMacLessThanOrEqualTo(String value) {
			addCriterion("mac <=", value, "mac");
			return (Criteria) this;
		}

		public Criteria andMacLike(String value) {
			addCriterion("mac like", value, "mac");
			return (Criteria) this;
		}

		public Criteria andMacNotLike(String value) {
			addCriterion("mac not like", value, "mac");
			return (Criteria) this;
		}

		public Criteria andMacIn(List<String> values) {
			addCriterion("mac in", values, "mac");
			return (Criteria) this;
		}

		public Criteria andMacNotIn(List<String> values) {
			addCriterion("mac not in", values, "mac");
			return (Criteria) this;
		}

		public Criteria andMacBetween(String value1, String value2) {
			addCriterion("mac between", value1, value2, "mac");
			return (Criteria) this;
		}

		public Criteria andMacNotBetween(String value1, String value2) {
			addCriterion("mac not between", value1, value2, "mac");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_user_online
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_user_online
     *
     * @mbggenerated do_not_delete_during_merge Sat Feb 04 16:01:24 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}