package com.goldcard.goldcardiot.models;

public class SysUserOnline {
	
	// add pojo
	private String userName; //用户名称
	private String deptName; //部门名称
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_online.id
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_online.user_id
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_online.stime
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	private String stime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_online.etime
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	private String etime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_online.session_id
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	private String sessionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_online.fm
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	private String fm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_online.ip
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_online.mac
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	private String mac;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_online.remark
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_online.id
	 * @return  the value of sys_user_online.id
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_online.id
	 * @param id  the value for sys_user_online.id
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_online.user_id
	 * @return  the value of sys_user_online.user_id
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_online.user_id
	 * @param userId  the value for sys_user_online.user_id
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_online.stime
	 * @return  the value of sys_user_online.stime
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public String getStime() {
		return stime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_online.stime
	 * @param stime  the value for sys_user_online.stime
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public void setStime(String stime) {
		this.stime = stime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_online.etime
	 * @return  the value of sys_user_online.etime
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public String getEtime() {
		return etime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_online.etime
	 * @param etime  the value for sys_user_online.etime
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public void setEtime(String etime) {
		this.etime = etime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_online.session_id
	 * @return  the value of sys_user_online.session_id
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public String getSessionId() {
		return sessionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_online.session_id
	 * @param sessionId  the value for sys_user_online.session_id
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_online.fm
	 * @return  the value of sys_user_online.fm
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public String getFm() {
		return fm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_online.fm
	 * @param fm  the value for sys_user_online.fm
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public void setFm(String fm) {
		this.fm = fm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_online.ip
	 * @return  the value of sys_user_online.ip
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_online.ip
	 * @param ip  the value for sys_user_online.ip
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_online.mac
	 * @return  the value of sys_user_online.mac
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public String getMac() {
		return mac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_online.mac
	 * @param mac  the value for sys_user_online.mac
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public void setMac(String mac) {
		this.mac = mac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_online.remark
	 * @return  the value of sys_user_online.remark
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_online.remark
	 * @param remark  the value for sys_user_online.remark
	 * @mbggenerated  Wed Mar 22 17:45:18 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}