package com.goldcard.goldcardiot.dao;

import com.goldcard.goldcardiot.models.SysCodeTable;
import com.goldcard.goldcardiot.models.SysCodeTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysCodeTableMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_code_table
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int countByExample(SysCodeTableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_code_table
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int deleteByExample(SysCodeTableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_code_table
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_code_table
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int insert(SysCodeTable record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_code_table
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int insertSelective(SysCodeTable record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_code_table
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	List<SysCodeTable> selectByExample(SysCodeTableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_code_table
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	SysCodeTable selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_code_table
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int updateByExampleSelective(@Param("record") SysCodeTable record, @Param("example") SysCodeTableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_code_table
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int updateByExample(@Param("record") SysCodeTable record, @Param("example") SysCodeTableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_code_table
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int updateByPrimaryKeySelective(SysCodeTable record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_code_table
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int updateByPrimaryKey(SysCodeTable record);
}