package com.goldcard.goldcardiot.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.goldcard.goldcardiot.models.SysDeptType;
import com.goldcard.goldcardiot.models.SysDeptTypeExample;

public interface SysDeptTypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dept_type
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int countByExample(SysDeptTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dept_type
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int deleteByExample(SysDeptTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dept_type
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dept_type
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int insert(SysDeptType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dept_type
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int insertSelective(SysDeptType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dept_type
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	List<SysDeptType> selectByExample(SysDeptTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dept_type
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	SysDeptType selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dept_type
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int updateByExampleSelective(@Param("record") SysDeptType record, @Param("example") SysDeptTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dept_type
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int updateByExample(@Param("record") SysDeptType record, @Param("example") SysDeptTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dept_type
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int updateByPrimaryKeySelective(SysDeptType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dept_type
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int updateByPrimaryKey(SysDeptType record);
	
	/**
	 * 心一：根据部门id查询部门类型列表
	 * @return
	 */
	List<Map<String,Object>> findSysDeptTyptByDeptId(Map<String,Object> paraMap);
	/**
	 * 心一：最大ID值
	 * @return
	 */
	int findMaxId();
}