package com.goldcard.goldcardiot.dao;

import com.goldcard.goldcardiot.models.SysRoleAndUser;
import com.goldcard.goldcardiot.models.SysRoleAndUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRoleAndUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_and_user
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int countByExample(SysRoleAndUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_and_user
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int deleteByExample(SysRoleAndUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_and_user
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_and_user
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int insert(SysRoleAndUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_and_user
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int insertSelective(SysRoleAndUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_and_user
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	List<SysRoleAndUser> selectByExample(SysRoleAndUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_and_user
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	SysRoleAndUser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_and_user
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int updateByExampleSelective(@Param("record") SysRoleAndUser record,
			@Param("example") SysRoleAndUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_and_user
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int updateByExample(@Param("record") SysRoleAndUser record, @Param("example") SysRoleAndUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_and_user
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int updateByPrimaryKeySelective(SysRoleAndUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_and_user
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int updateByPrimaryKey(SysRoleAndUser record);
	/**
	 * 心一：删除信息
	 * @param userId： 用户ID
	 * @return
	 */
	int deleteByUserId(Integer userId);
}