package com.goldcard.goldcardiot.dao;

import com.goldcard.goldcardiot.models.SysRoleAndRight;
import com.goldcard.goldcardiot.models.SysRoleAndRightExample;
import com.goldcard.goldcardiot.models.SysUserAndRight;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRoleAndRightMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_and_right
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int countByExample(SysRoleAndRightExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_and_right
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int deleteByExample(SysRoleAndRightExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_and_right
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_and_right
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int insert(SysRoleAndRight record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_and_right
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int insertSelective(SysRoleAndRight record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_and_right
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	List<SysRoleAndRight> selectByExample(SysRoleAndRightExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_and_right
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	SysRoleAndRight selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_and_right
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int updateByExampleSelective(@Param("record") SysRoleAndRight record,
			@Param("example") SysRoleAndRightExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_and_right
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int updateByExample(@Param("record") SysRoleAndRight record, @Param("example") SysRoleAndRightExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_and_right
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int updateByPrimaryKeySelective(SysRoleAndRight record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_and_right
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int updateByPrimaryKey(SysRoleAndRight record);
	/**
	 * 心一：批量插入当前角色权限信息
	 * @param roleAndRightList
	 */
	void saveSysRoleAndRightByList(List<SysRoleAndRight> roleAndRightList);
}