package com.goldcard.goldcardiot.dao;

import com.goldcard.goldcardiot.models.SysRightAndDept;
import com.goldcard.goldcardiot.models.SysRightAndDeptExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRightAndDeptMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_right_and_dept
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int countByExample(SysRightAndDeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_right_and_dept
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int deleteByExample(SysRightAndDeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_right_and_dept
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int insert(SysRightAndDept record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_right_and_dept
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int insertSelective(SysRightAndDept record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_right_and_dept
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	List<SysRightAndDept> selectByExample(SysRightAndDeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_right_and_dept
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int updateByExampleSelective(@Param("record") SysRightAndDept record,
			@Param("example") SysRightAndDeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_right_and_dept
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int updateByExample(@Param("record") SysRightAndDept record, @Param("example") SysRightAndDeptExample example);
}