package com.goldcard.goldcardiot.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.goldcard.goldcardiot.models.SysUserAndRight;
import com.goldcard.goldcardiot.models.SysUserAndRightExample;

public interface SysUserAndRightMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_and_right
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int countByExample(SysUserAndRightExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_and_right
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int deleteByExample(SysUserAndRightExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_and_right
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_and_right
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int insert(SysUserAndRight record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_and_right
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int insertSelective(SysUserAndRight record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_and_right
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	List<SysUserAndRight> selectByExample(SysUserAndRightExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_and_right
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	SysUserAndRight selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_and_right
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int updateByExampleSelective(@Param("record") SysUserAndRight record,
			@Param("example") SysUserAndRightExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_and_right
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int updateByExample(@Param("record") SysUserAndRight record, @Param("example") SysUserAndRightExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_and_right
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int updateByPrimaryKeySelective(SysUserAndRight record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_and_right
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int updateByPrimaryKey(SysUserAndRight record);
	/**
	 * 心一：条件查询信息
	 * @param paramMap
	 * @return
	 */
	List<SysUserAndRight> findListByCondition(Map<String,Object> paramMap);
	
	/**
	 * 心一：保存用户权限集合
	 * @param userAndRights
	 */
	void saveSysUserAndRightByList(List<SysUserAndRight> userAndRights);
	/**
	 * 心一：根据用户id批量删除
	 * @param userId：用户id
	 */
	void deleteByUserId(Integer userId);
}