package com.goldcard.goldcardiot.dao;

import com.goldcard.goldcardiot.models.SysUserType;
import com.goldcard.goldcardiot.models.SysUserTypeExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SysUserTypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_type
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int countByExample(SysUserTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_type
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int deleteByExample(SysUserTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_type
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_type
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int insert(SysUserType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_type
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int insertSelective(SysUserType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_type
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	List<SysUserType> selectByExample(SysUserTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_type
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	SysUserType selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_type
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int updateByExampleSelective(@Param("record") SysUserType record, @Param("example") SysUserTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_type
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int updateByExample(@Param("record") SysUserType record, @Param("example") SysUserTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_type
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int updateByPrimaryKeySelective(SysUserType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_type
	 * @mbggenerated  Sat Feb 04 16:21:42 CST 2017
	 */
	int updateByPrimaryKey(SysUserType record);
	/**
	 * 心一：根据部门类型查询用户类型
	 * @return
	 */
	List<SysUserType> findSysUserTypeListByDeptId(SysUserType sysUserType);
	/**
	 * 心一：分页查询
	 * @param paraMap
	 * @return
	 */
	List<SysUserType> findSysUserTypePageByConditions(Map<String,Object> paraMap);
	int findSysUserTypeCountByConditions(Map<String,Object> paraMap);
	/**
	 * 心一：条件查询系统用户类型的个数
	 * @param sysUserType
	 * @return
	 */
	int findCountTypeNameById(SysUserType sysUserType);
}